trigger: none  # No automatic trigger

pr: none  # No PR trigger

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'terraform-azure-connection'

stages:
- stage: Terraform_Deployment
  displayName: 'Deploy AI Infrastructure'
  jobs:
  - job: Deploy
    displayName: 'Run Terraform Deployment'
    steps:
    - script: |
        echo "Installing Terraform..."
        sudo apt update && sudo apt install -y unzip
        curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        terraform -version
      displayName: 'Install Terraform'

    - script: |
        echo "Initializing Terraform..."
        terraform init \
          -backend-config="resource_group_name=terraform-backend-rg" \
          -backend-config="storage_account_name=terraformbackendai" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=terraform.tfstate"
      displayName: 'Terraform Init'

    - script: |
        echo "Running Terraform Plan..."
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'

    - script: |
        echo "Applying Terraform Plan..."
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
