name: Deploy Azure Infrastructure

on: 
  workflow_dispatch:

permissions: 
  id-token: write
  contents: read

jobs:  
  deploy:    
    runs-on: ubuntu-latest    
    steps:      
      - name: Checkout Repository        
        uses: actions/checkout@v3      

      - name: Setup Terraform        
        uses: hashicorp/setup-terraform@v2        
        with:          
          terraform_version: 1.5.0      

      - name: Azure Login        
        uses: azure/login@v1        
        with:          
          client-id: ${{ secrets.AZURE_CLIENT_ID }}          
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}          
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}      
          
      - name: Show Current Directory Path
        run: pwd
        
      - name: List All Files in Repo
        run: ls -R
        


      - name: Initialize Terraform        
        run: terraform init        
        working-directory: azure/azurevm-storage      

      - name: Validate Terraform        
        run: terraform validate        
        working-directory: azure/azurevm-storage      

      - name: Plan Terraform        
        run: terraform plan -out=tfplan        
        working-directory: azure/azurevm-storage      

      - name: Apply Terraform        
        run: terraform apply -auto-approve tfplan        
        working-directory: azure/azurevm-storage
